# Generated by Django 4.2.7 on 2025-09-25 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0002_alter_suggestion_category'),
    ]

    operations = [
    ]
