# Generated by Django 4.2.7 on 2025-09-25 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0003_make_category_optional'),
    ]

    operations = [
    ]
