# Generated by Django 4.2.7 on 2025-09-24 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openweather', 'OpenWeatherMap'), ('google_translate', 'Google Translate'), ('openai', 'OpenAI GPT'), ('google_vision', 'Google Vision'), ('twilio_sms', 'Twilio SMS'), ('azure_speech', 'Azure Speech'), ('pagasa', 'PAGASA Weather')], max_length=50, unique=True)),
                ('api_key', models.CharField(help_text='API Key (will be encrypted)', max_length=500)),
                ('api_secret', models.CharField(blank=True, help_text='API Secret (optional)', max_length=500)),
                ('base_url', models.URLField(blank=True, help_text='Custom base URL if needed')),
                ('is_active', models.BooleanField(default=True)),
                ('rate_limit', models.IntegerField(default=1000, help_text='Requests per hour limit')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requests_made_today', models.IntegerField(default=0)),
                ('last_request_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['provider'],
            },
        ),
        migrations.CreateModel(
            name='ProactiveAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('alert_type', models.CharField(choices=[('weather', 'Weather Alert'), ('emergency', 'Emergency Alert'), ('announcement', 'Barangay Announcement'), ('reminder', 'Service Reminder'), ('maintenance', 'System Maintenance')], default='announcement', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=1, help_text='1=Low, 2=Medium, 3=High, 4=Critical')),
                ('target_language', models.CharField(choices=[('en', 'English'), ('fil', 'Filipino'), ('both', 'Both')], default='both', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave empty for no expiration', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='chatbot/images/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('ai_analysis', models.TextField(blank=True, help_text='AI analysis of the image')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to='chatbot.chatsession')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
