# Generated by Django 4.2.7 on 2025-09-19 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_filipino', models.CharField(help_text='Filipino translation', max_length=100)),
                ('description', models.TextField()),
                ('description_filipino', models.TextField(help_text='Filipino translation')),
                ('requirements', models.TextField(help_text='Requirements in English')),
                ('requirements_filipino', models.TextField(help_text='Requirements in Filipino')),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Service fee in PHP', max_digits=10)),
                ('processing_time', models.CharField(choices=[('same_day', 'Same Day / Araw din'), ('1_day', '1 Business Day / 1 Araw ng Trabaho'), ('3_days', '3 Business Days / 3 Araw ng Trabaho'), ('1_week', '1 Week / 1 Linggo'), ('2_weeks', '2 Weeks / 2 Linggo')], default='3_days', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_online_available', models.BooleanField(default=False, help_text='Can be requested online')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_filipino', models.CharField(help_text='Filipino translation', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('description_filipino', models.TextField(blank=True, help_text='Filipino translation')),
                ('icon', models.CharField(default='fas fa-file', help_text='FontAwesome icon class', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('purpose', models.TextField(help_text='Purpose of the service request')),
                ('purpose_filipino', models.TextField(blank=True, help_text='Purpose in Filipino (optional)')),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent / Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Review / Naghihintay ng Review'), ('processing', 'Processing / Pinoproseso'), ('ready', 'Ready for Pickup / Handa nang Kunin'), ('completed', 'Completed / Tapos na'), ('rejected', 'Rejected / Hindi Tinanggap')], default='pending', max_length=15)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for staff')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('pickup_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='services.service')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='service_attachments/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='services.servicerequest')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory'),
        ),
    ]
