# Generated by Django 4.2.7 on 2025-09-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position_portfolio',
            field=models.CharField(blank=True, help_text='Specific portfolio or assignment details', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('resident', 'Resident'), ('secretary', 'Barangay Secretary'), ('chairman', 'Barangay Chairman'), ('tanod_head', 'Barangay Tanod Head'), ('kagawad_peace', 'Kagawad - Peace & Order'), ('kagawad_infra', 'Kagawad - Infrastructure'), ('kagawad_health', 'Kagawad - Health'), ('kagawad_social', 'Kagawad - Social Services'), ('kagawad_sanitation', 'Kagawad - Sanitation'), ('kagawad_environment', 'Kagawad - Environment'), ('lupon_chair', 'Lupon Tagapamayapa - Chairperson'), ('lupon_member', 'Lupon Tagapamayapa - Member'), ('bhw', 'Barangay Health Worker'), ('sk_chair', 'SK Chairperson'), ('vaw_officer', 'VAW Desk Officer'), ('badac_focal', 'BADAC Focal Person'), ('bdrrmc_focal', 'BDRRMC Focal Person'), ('animal_control', 'Animal Control Officer')], default='resident', max_length=20),
        ),
    ]
