# Generated by Django 4.2.7 on 2025-09-22 02:35

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_position_portfolio_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=accounts.models.user_verification_upload_path)),
                ('document_type', models.CharField(blank=True, help_text='e.g., Barangay ID, Utility Bill', max_length=50, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
