# Generated by Django 4.2.7 on 2025-09-23 13:16

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userverificationdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Upload your photo (required for registration)', null=True, upload_to=accounts.models.user_profile_photo_upload_path),
        ),
    ]
