# Generated by Django 4.2.7 on 2025-09-24 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_latitude_user_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangayArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Street/Area name', max_length=100, unique=True)),
                ('zone', models.CharField(blank=True, help_text='Zone designation (e.g., Zone 1, Zone 2)', max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Barangay Area',
                'verbose_name_plural': 'Barangay Areas',
                'ordering': ['zone', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ResidencyValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_status', models.CharField(choices=[('pending', 'Pending Validation'), ('valid_location', 'Valid Location'), ('invalid_location', 'Invalid Location'), ('valid_address', 'Valid Address'), ('invalid_address', 'Invalid Address'), ('auto_approved', 'Auto Approved'), ('requires_manual', 'Requires Manual Review')], default='pending', max_length=20)),
                ('address_status', models.CharField(choices=[('pending', 'Pending Validation'), ('valid_location', 'Valid Location'), ('invalid_location', 'Invalid Location'), ('valid_address', 'Valid Address'), ('invalid_address', 'Invalid Address'), ('auto_approved', 'Auto Approved'), ('requires_manual', 'Requires Manual Review')], default='pending', max_length=20)),
                ('validation_notes', models.TextField(blank=True, null=True)),
                ('last_validated', models.DateTimeField(auto_now=True)),
                ('auto_validation_score', models.IntegerField(default=0, help_text='Automated validation score (0-100)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='residency_validation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
