# Generated by Django 4.2.7 on 2025-09-24 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_barangayarea_residencyvalidation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePhotoValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_encoding', models.JSONField(blank=True, help_text='Stored face encoding for duplicate detection', null=True)),
                ('has_face', models.BooleanField(default=False, help_text='Photo contains a detectable human face')),
                ('is_real_face', models.BooleanField(default=False, help_text='Face appears to be a real person (not cartoon/drawing)')),
                ('confidence_score', models.FloatField(default=0.0, help_text='Face detection confidence (0.0-1.0)')),
                ('validation_notes', models.TextField(blank=True, help_text='AI validation feedback', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo_validation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
