# Generated by Django 4.2.24 on 2025-09-24 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profilephotovalidation'),
    ]

    operations = [
    ]
