# Generated by Django 4.2.7 on 2025-09-25 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Announcement title', max_length=200)),
                ('content', models.TextField(help_text='Detailed announcement content')),
                ('category', models.CharField(choices=[('general', 'General Announcement'), ('meeting', 'Barangay Meeting'), ('event', 'Community Event'), ('alert', 'Important Alert'), ('service', 'Service Update'), ('health', 'Health Advisory'), ('safety', 'Safety Notice'), ('maintenance', 'Maintenance Notice')], default='general', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When to publish this announcement')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Optional expiry date', null=True)),
                ('is_published', models.BooleanField(default=True, help_text='Make announcement visible to public')),
                ('is_pinned', models.BooleanField(default=False, help_text='Pin announcement to top')),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('created', 'Announcement Created'), ('updated', 'Announcement Updated'), ('published', 'Announcement Published'), ('expired', 'Announcement Expired')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='announcements.announcement')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement Notification',
                'verbose_name_plural': 'Announcement Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
