# Generated by Django 4.2.7 on 2025-09-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, help_text='Announcement image', null=True, upload_to='announcements/'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(blank=True, help_text='Detailed announcement content'),
        ),
    ]
