# Generated by Django 4.2.7 on 2025-09-25 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcement_image_alter_announcement_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementnotification',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_notifications', to='announcements.announcement'),
        ),
    ]
