# Generated by Django 4.2.7 on 2025-09-25 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcements', '0003_alter_announcementnotification_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved by Chairman'), ('rejected', 'Rejected by Chairman')], default='pending', help_text='Chairman approval status', max_length=20),
        ),
        migrations.AddField(
            model_name='announcement',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When this was approved', null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Chairman who approved this announcement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection'),
        ),
    ]
