# Generated by Django 4.2.7 on 2025-09-20 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaints', '0002_alter_complaint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='accepted_at',
            field=models.DateTimeField(blank=True, help_text='When complaint was accepted/assigned', null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='assignment_due',
            field=models.DateTimeField(blank=True, help_text='When assignment should be completed', null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='assignment_notes',
            field=models.TextField(blank=True, help_text='Assignment or referral notes'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='response_due',
            field=models.DateTimeField(blank=True, help_text='When response is due', null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('emergency', 'Emergency')], default='normal', max_length=10),
        ),
        migrations.CreateModel(
            name='CategoryAssignmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_assignee_role', models.CharField(choices=[('tanod_head', 'Barangay Tanod Head'), ('kagawad_peace', 'Kagawad - Peace & Order'), ('kagawad_infra', 'Kagawad - Infrastructure'), ('kagawad_health', 'Kagawad - Health'), ('kagawad_social', 'Kagawad - Social Services'), ('kagawad_sanitation', 'Kagawad - Sanitation'), ('kagawad_environment', 'Kagawad - Environment'), ('lupon_chair', 'Lupon Tagapamayapa - Chairperson'), ('bhw', 'Barangay Health Worker'), ('sk_chair', 'SK Chairperson'), ('vaw_officer', 'VAW Desk Officer'), ('badac_focal', 'BADAC Focal Person'), ('bdrrmc_focal', 'BDRRMC Focal Person'), ('animal_control', 'Animal Control Officer'), ('secretary', 'Barangay Secretary'), ('chairman', 'Barangay Chairman')], max_length=20)),
                ('backup_assignee_role', models.CharField(blank=True, choices=[], max_length=20, null=True)),
                ('is_sensitive', models.BooleanField(default=False, help_text='Requires confidential handling')),
                ('requires_referral', models.BooleanField(default=False, help_text='Usually needs external referral')),
                ('escalation_notes', models.TextField(blank=True, help_text='Instructions for escalation')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_rules', to='complaints.complaintcategory')),
            ],
        ),
    ]
