# Generated by Django 4.2.7 on 2025-09-20 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_accepted_at_complaint_assignment_due_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryassignmentrule',
            name='backup_assignee_role',
            field=models.CharField(blank=True, choices=[('tanod_head', 'Barangay Tanod Head'), ('kagawad_peace', 'Kagawad - Peace & Order'), ('kagawad_infra', 'Kagawad - Infrastructure'), ('kagawad_health', 'Kagawad - Health'), ('kagawad_social', 'Kagawad - Social Services'), ('kagawad_sanitation', 'Kagawad - Sanitation'), ('kagawad_environment', 'Kagawad - Environment'), ('lupon_chair', 'Lupon Tagapamayapa - Chairperson'), ('lupon_member', 'Lupon Tagapamayapa - Member'), ('bhw', 'Barangay Health Worker'), ('sk_chair', 'SK Chairperson'), ('vaw_officer', 'VAW Desk Officer'), ('badac_focal', 'BADAC Focal Person'), ('bdrrmc_focal', 'BDRRMC Focal Person'), ('animal_control', 'Animal Control Officer'), ('secretary', 'Barangay Secretary'), ('chairman', 'Barangay Chairman')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='categoryassignmentrule',
            name='default_assignee_role',
            field=models.CharField(choices=[('tanod_head', 'Barangay Tanod Head'), ('kagawad_peace', 'Kagawad - Peace & Order'), ('kagawad_infra', 'Kagawad - Infrastructure'), ('kagawad_health', 'Kagawad - Health'), ('kagawad_social', 'Kagawad - Social Services'), ('kagawad_sanitation', 'Kagawad - Sanitation'), ('kagawad_environment', 'Kagawad - Environment'), ('lupon_chair', 'Lupon Tagapamayapa - Chairperson'), ('lupon_member', 'Lupon Tagapamayapa - Member'), ('bhw', 'Barangay Health Worker'), ('sk_chair', 'SK Chairperson'), ('vaw_officer', 'VAW Desk Officer'), ('badac_focal', 'BADAC Focal Person'), ('bdrrmc_focal', 'BDRRMC Focal Person'), ('animal_control', 'Animal Control Officer'), ('secretary', 'Barangay Secretary'), ('chairman', 'Barangay Chairman')], max_length=20),
        ),
    ]
