# Generated by Django 4.2.7 on 2025-09-20 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaints', '0004_alter_categoryassignmentrule_backup_assignee_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='resolution_notes',
            field=models.TextField(blank=True, help_text='Detailed notes about how the complaint was resolved'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolution_proof',
            field=models.FileField(blank=True, help_text='Photo or document proof of complaint resolution (required for resolved status)', null=True, upload_to='resolution_proofs/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolved_by',
            field=models.ForeignKey(blank=True, help_text='Chairman or official who resolved the complaint', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_complaints', to=settings.AUTH_USER_MODEL),
        ),
    ]
