# Generated by Django 4.2.7 on 2025-09-20 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaints', '0005_add_resolution_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When complaint was approved by secretary', null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Secretary who approved this complaint', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Approved by secretary for chairman review'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if complaint is not approved'),
        ),
    ]
