# Generated by Django 4.2.7 on 2025-09-20 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_add_secretary_approval'),
    ]

    operations = [
    ]
