# Generated by Django 4.2.7 on 2025-09-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_add_secretary_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='is_approved',
            field=models.BooleanField(blank=True, default=None, help_text='Approved by secretary for chairman review (None=pending, True=approved, False=rejected)', null=True),
        ),
    ]
