# Generated by Django 4.2.7 on 2025-09-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_alter_complaint_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintcomment',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional file attachment (proof, documents, etc.)', null=True, upload_to='comment_attachments/%Y/%m/'),
        ),
    ]
