# Generated by Django 4.2.7 on 2025-09-21 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_complaintcomment_attachment'),
    ]

    operations = [
    ]
