# Generated by Django 4.2.7 on 2025-09-24 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaints', '0010_add_comment_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='anonymous_contact',
            field=models.CharField(blank=True, help_text='Optional contact info for anonymous complaints', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='Anonymous complaint - no complainant identity revealed'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complainant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL),
        ),
    ]
