# Generated by Django 4.2.7 on 2025-09-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('complaint_created', 'Complaint Created'), ('complaint_updated', 'Complaint Updated'), ('complaint_resolved', 'Complaint Resolved'), ('complaint_rejected', 'Complaint Rejected'), ('feedback_received', 'Feedback Received'), ('user_approved', 'User Approved'), ('system_announcement', 'System Announcement')], max_length=50),
        ),
    ]
